language: node_js
node_js:
  - 10
after_success:
  - mkdir build
  - cp -R build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
